# Generated by Django 3.1.5 on 2021-03-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_signupcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupcode',
            name='code',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='signupcode',
            name='ipaddr',
            field=models.GenericIPAddressField(verbose_name='ip address'),
        ),
    ]
