# Generated by Django 3.1.5 on 2021-03-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210324_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='total_rating_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_rating_value',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True),
        ),
    ]
