# Generated by Django 3.1.5 on 2021-03-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210322_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_book',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
